export default {
  colors: {
    text: "white",
    headerBackground: "#23272A",
    headerText: "white",
    paperBackgroundColor: "#23272A",
    paperHoverBackgroundColor: "#2C2F33",
    paperHeadingColor: "#8A6AFD",
    paperHoverHeadingColor: "#7289DA",
    paperBorderColor: "#7289DA",
    paperDescriptionColor: "white",
    collectionBackgroundColor: "#2C2F33",
    collectionHeading: "white",
    collectionDescription: "white",
    breadcrumbLinkTextColor: "#7289DA",
    breadcrumbHoverLinkTextColor: "#8A6AFD",
    breadcrumbTextColor: "white",
    articleTextColor: "white",
    articleDescriptionColor: "white",
    background: "#fff",
    primary: "#639",
    secondary: "#ff6347",
    muted: "#8f919d",
    searchTextColor: "rgba(255,255,255,0.7)",
    searchTextFocusColor: "#3a3c4c",
    searchTextPlaceholderColor: "white",
    searchTextFocusPlaceholderColor: "black",
    comboboxColor: "white",
    iconColor: "#828A97",
    logoColor: "white",
    footerTextColor: "white",
    footerTextHoverColor: "white",
  },
  radii: [0, 2, 4, 8],
  fonts: {
    body: "Quicksand, sans-serif",
    heading: "Quicksand, sans-serif",
    monospace: "Menlo, monospace",
  },
  fontWeights: {
    body: 400,
    heading: 700,
    bold: 700,
  },
  lineHeights: {
    small: 1.2,
    body: 1.5,
    heading: 1.125,
  },
  fontSizes: [12, 14, 16, 20, 24, 32, 48, 64, 72],
  space: [0, 4, 8, 16, 32, 64, 128, 256, 512],
  styles: {
    h1: {
      color: "white",
      fontFamily: "heading",
      fontWeight: "heading",
      lineHeight: "heading",
      marginTop: 0,
      marginBottom: 3,
    },
    h2: {
      color: "white",
      fontFamily: "heading",
      fontWeight: "heading",
      lineHeight: "heading",
      marginTop: 0,
      marginBottom: 3,
    },
    h3: {
      color: "white",
      fontFamily: "heading",
      fontWeight: "heading",
      lineHeight: "heading",
      marginTop: 0,
      marginBottom: 3,
    },
    p: {
      color: "white"
    },
    a: {
      color: "primary",
      ":hover, :focus": {
        color: "secondary",
      },
    },
    blockquote: {
      marginLeft: "1.75rem",
    },
    // more styles can be added as needed
  },
}
